// Generated by CoffeeScript 1.7.1
(function() {
  var Q, coffee_bin, main, os;

  require('coffee-script/register');

  require('colors');

  os = require('../lib/os');

  Q = require('q');

  coffee_bin = os.path.resolve(os.path.join('node_modules', '.bin', 'coffee'));

  main = function() {
    var builder, setup;
    switch (process.argv[2]) {
      case 'setup':
        setup = require('./setup');
        return setup.start();
      case 'build':
        builder = require('./builder');
        return builder.start();
    }
  };

  main();

}).call(this);
